name: Build & Push Docker Image

on:
  push:

jobs:
  build:
    name: Docker build & push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set ENV to build
        run: |
          tag=$(echo ${{github.ref}} | sed -e 's/refs\/heads\///')
          port=8022
          env=dev
          if [[ ${{github.ref}} == 'refs/tags/'* ]]; then
            tag=$(echo ${{github.ref}} | sed -e 's/refs\/tags\///')
            port=8020
            env=prod
          elif [[ ${{github.ref}} == 'refs/heads/main' ]]; then
            tag=latest
            port=8021
            env=stage
          fi
        
          echo "REPOSITORY_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "ENV=$env" >> $GITHUB_ENV
          echo "PORT=$port" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:$tag" >> $GITHUB_ENV
      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64, linux/arm64
          target: prod
          push: true
          tags: ${{env.DOCKER_IMAGE_NAME}}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull ${{env.DOCKER_IMAGE_NAME}}
            
            docker run -it --rm --name ${{env.REPOSITORY_NAME}}-$ENV -p $PORT:80 -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e APP_SECRET=${{ secrets.APP_SECRET }} -d ${{env.DOCKER_IMAGE_NAME}}
           
            # create database
            docker exec -ti cs-cosmetics symfony console d:d:c --if-not-exists
            
            # run migrations
            docker exec -ti cs-cosmetics symfony console d:m:m -n
            
            # list running containers
            docker ps
