name: Build & Push Docker Image

on:
  push:
    branches:
      - main
    tags: '*'

jobs:
  build:
    name: Docker build & push image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set env
        run: echo "REPOSITORY_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          target: prod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{env.REPOSITORY_NAME}}:latest
      - name: Build and push Docker image
        if: github.ref == 'refs/tags/*'
        uses: docker/build-push-action@v5
        with:
          target: prod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{env.REPOSITORY_NAME}}:${{github.ref}}
